// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZorgtechnologieProduct.API.Data;

#nullable disable

namespace ZorgtechnologieProduct.API.Migrations
{
    [DbContext(typeof(ZorgtechnologieDbContext))]
    [Migration("20250625223719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Zorginstellingslocatie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Plaats")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Zorginstellingslocaties");
                });

            modelBuilder.Entity("ZorgtechnologieProduct.Domain.ZorgtechnologieProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Eigenschappen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ZorgtechnologieProducten");
                });

            modelBuilder.Entity("ZorgtechnologieProduct.Domain.ZorgtechnologieProductItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AanschafDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("AanschafKosten")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("InGebruik")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LocatieId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ZorgtechnologieProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("ZorgtechnologieProductItems");
                });
#pragma warning restore 612, 618
        }
    }
}
