// <auto-generated />
using System;
using BCImplementatie.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BCImplementatie.Migrations
{
    [DbContext(typeof(ImplementatieDbContext))]
    [Migration("20250628122912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BCImplementatie.Domain.Entities.CareNeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AdviesZorgtechnologieProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<Guid>("GebruikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NeedCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NeedDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikId");

                    b.HasIndex("NeedCategoryName");

                    b.ToTable("CareNeeds");
                });

            modelBuilder.Entity("BCImplementatie.Domain.Entities.Ervaring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GebruikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observatie")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikId");

                    b.ToTable("Ervaringen");
                });

            modelBuilder.Entity("BCImplementatie.Domain.Entities.Gebruik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InGebruik")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ZorgtechnologieProductItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Gebruiken");
                });

            modelBuilder.Entity("BCImplementatie.Domain.ValueObjects.NeedCategory", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Name");

                    b.ToTable("NeedCategories");

                    b.HasData(
                        new
                        {
                            Name = "Gezondheid",
                            Description = "Gezondheidszorg gerelateerde behoeften"
                        },
                        new
                        {
                            Name = "Onderwijs",
                            Description = "Onderwijs gerelateerde behoeften"
                        });
                });

            modelBuilder.Entity("BCImplementatie.Domain.Entities.CareNeed", b =>
                {
                    b.HasOne("BCImplementatie.Domain.Entities.Gebruik", "Gebruik")
                        .WithMany("CareNeeds")
                        .HasForeignKey("GebruikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BCImplementatie.Domain.ValueObjects.NeedCategory", "Category")
                        .WithMany()
                        .HasForeignKey("NeedCategoryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Gebruik");
                });

            modelBuilder.Entity("BCImplementatie.Domain.Entities.Ervaring", b =>
                {
                    b.HasOne("BCImplementatie.Domain.Entities.Gebruik", "Gebruik")
                        .WithMany("Ervaringen")
                        .HasForeignKey("GebruikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruik");
                });

            modelBuilder.Entity("BCImplementatie.Domain.Entities.Gebruik", b =>
                {
                    b.Navigation("CareNeeds");

                    b.Navigation("Ervaringen");
                });
#pragma warning restore 612, 618
        }
    }
}
