services:
  electronicclientdossier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: electronicclientdossier
    ports:
      - "8080:80"
    environment:
      APP_MODE: CLOUD

    
