<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- haal de standaard NuGet-fallback paden weg -->
		<RestoreFallbackFolders></RestoreFallbackFolders>
		<!-- én eventuele extra fallback folders uitschakelen -->
		<RestoreAdditionalProjectFallbackFolders></RestoreAdditionalProjectFallbackFolders>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controllers\" />
	</ItemGroup>

</Project>
