FROM continuumio/miniconda3

WORKDIR /app

COPY environment.yaml .
COPY requirements.txt .

RUN conda env create -f environment.yaml

SHELL ["/bin/bash", "--login", "-c"]
RUN conda run -n advice pip install --no-cache-dir -r requirements.txt

# Copy your app code + model file into image
COPY . .

ENV FLASK_APP=advice
ENV FLASK_ENV=testing

CMD ["conda", "run", "-n", "advice", "gunicorn","--bind", "0.0.0.0:5000","advice:app"]
