version: '3.8'

services:
  bcimplementatie:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bcimplementatie
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__ImplementatieDb: "Server=tcp:implementatiesv.database.windows.net,1433;Initial Catalog=Implementatiedb;User ID=impadmin;Password=i2ukdJN19mVAXg;TrustServerCertificate=False;Encrypt=True;"

      # Optioneel: Service Principal voor DefaultAzureCredential in Docker
      # AZURE_CLIENT_ID: "<je-SP-app-id>"
      # AZURE_TENANT_ID: "<je-tenant-id>"
      # AZURE_CLIENT_SECRET: "<je-SP-secret>"
